Update pages
Vanilla-OS/handbook pull request #42
Opened 2023-01-12 14:58 UTC by kbdharun

Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

## Changes

- Fix the Image in the latest guide.
- Update Steam, Flatpak, Driver Installation and Distrobox guides.
- Add Installing Drivers as DEBs Section.

2023-01-12 17:58 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +In Vanilla OS there are many ways to install applications. The easiest way is to use
```suggestion
In Vanilla OS there are many ways to install Steam. The easiest way is to use
```

2023-01-12 18:03 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +- On 21 August 2018, Steam introduced the [Proton](https://github.com/ValveSoftware/Proton) project, which allows you to run Windows games on Linux. It is an essential feature for Linux gamers as it
```suggestion
- On 21 August 2018, Steam introduced the [Proton](https://github.com/ValveSoftware/Proton) project, which allows you to run Windows games on Linux. It is an essential tool for Linux gamers as it extends the number of games available on the platform. Check out [**ProtonDB**](https://www.protondb.com) to see how well your favourite games work with Proton.
```

2023-01-12 18:05 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +[Distrobox](https://github.com/89luca89/distrobox). In our tests, Fedora is the best distro to run Steam in a container . We highly recommend using it to install Steam.
```suggestion
[Distrobox](https://github.com/89luca89/distrobox). In our tests, Fedora is the best distro to run Steam in a container. We highly recommend using it to install Steam.
```

2023-01-12 18:09 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +- On Ubuntu, we need to add the `multiverse` repository to our sources list using the follow:
```suggestion
- On Ubuntu, we need to add the `multiverse` repository to our sources list using the following command:
```

2023-01-12 18:14 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +- Now we can install Steam using the following command:
```suggestion
- We can now install Steam using the following command:
```

2023-01-12 18:15 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +Now we can install Steam using the following command:
```suggestion
- We can now install Steam using the following command:
```

2023-01-12 19:30 UTC, MonsterObserver requested changes
A bunch of small little fixes :)

2023-01-12 19:30 UTC, MonsterObserver commented on _posts/2023-01-07-install-steam.md
> +**Apx** is a package manager which installs software in containers thanks to
```suggestion
**apx** is a package manager which installs software in containers thanks to
```

2023-01-12 19:30 UTC, MonsterObserver commented on _posts/2022-12-09-install-flatpaks.md
> +Flatpak needs to know where to look for applications. The default and most popular repository for installing Flatpaks are Flathub, which can get added using the following command:
```suggestion
Flatpak needs to know where to look for applications. The default and most popular repository for installing Flatpaks is Flathub, which you can add using the following command:
```

2023-01-12 19:30 UTC, MonsterObserver commented on _posts/2022-12-10-install-additional-drivers.md
> +install. For example,  Installing the NVIDIA driver at version 525 can be done by executing the following command:
```suggestion
install. For example, installing the NVIDIA driver at version 525 can be done by executing the following command:
```

2023-01-12 19:30 UTC, MonsterObserver commented on _posts/2022-12-10-install-additional-drivers.md
> +sudo cp <path/to/driver.deb> /tmp
```suggestion
cp <path/to/driver.deb> /tmp
```

2023-01-13 01:44 UTC, kbdharun commented on _posts/2022-12-09-install-flatpaks.md
> +In this case, you will always need to run Flatpak commands inside the Apx container:
```suggestion
In this case, you will always need to run Flatpak commands inside the `apx` container:
```

2023-01-13 01:45 UTC, kbdharun commented on _posts/2022-12-09-install-flatpaks.md
> +There are two ways to install a Flatpak application: using _GNOME Software or through the command line_.
```suggestion
There are two ways to install a Flatpak applications using _GNOME Software or through the command line_.
```

2023-01-13 01:50 UTC, kbdharun commented on _posts/2022-12-10-install-additional-drivers.md
> +sudo cp <path/to/driver.deb> /tmp
Isn't sudo required here?

2023-01-13 12:54 UTC, merged